<a href="https://colab.research.google.com/github/Harsh152003/Reinforcement_Learning/blob/main/Exp_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import gym

env = gym.make("FrozenLake-v1")

n_state = env.observation_space.n
print("N states (4x4):", n_state)
n_action = env.action_space.n
print("M actions (U, D, L, R):", n_action)

env.reset()
print("\nFrozenLake-v0 Env")
env.render()

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don

N states (4x4): 16
M actions (U, D, L, R): 4

FrozenLake-v0 Env


In [26]:
# env model: we have knowledge about everything in the environment

import pprint
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(env.P)

# {
#     state1: {
#         action1: [(transition_prob, next_state, reward, done)],
#         action2: [(transition_prob, next_state, reward, done)],
#         action3: [(transition_prob, next_state, reward, done)],
#         action4: [(transition_prob, next_state, reward, done)],
#     },
#     state2: {
#         action1: [(transition_prob, next_state, reward, done)],
#         ...
#     }
#     ...
# }

{   0: {   0: [   (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 4, 0.0, False)],
           1: [   (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 4, 0.0, False),
                  (0.3333333333333333, 1, 0.0, False)],
           2: [   (0.3333333333333333, 4, 0.0, False),
                  (0.3333333333333333, 1, 0.0, False),
                  (0.3333333333333333, 0, 0.0, False)],
           3: [   (0.3333333333333333, 1, 0.0, False),
                  (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 0, 0.0, False)]},
    1: {   0: [   (0.3333333333333333, 1, 0.0, False),
                  (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 5, 0.0, True)],
           1: [   (0.3333333333333333, 0, 0.0, False),
                  (0.3333333333333333, 5, 0.0, True),
                  (0.3333333333333333, 2, 0.0, False)],
     

In [28]:
import numpy as np
import gym

def policy_evaluation(env, policy, gamma, theta, state_values):
    """
    policy_evaluation: 		estimate state values based on the policy

    @param env:       		OpenAI Gym environment
    @param policy:    		policy matrix containing actions and their probability in each state
    @param gamma:     		discount factor
    @param theta: 			evaluation will stop once values for all states are less than theta
    @param state_values: 	initial state values

    @return:         		new state values of the given policy
    """
    delta = theta*2
    state_len = env.observation_space.n  # Use observation_space.n for the number of states
    action_len = env.action_space.n  # Use action_space.n for the number of actions

    while (delta > theta):
        delta = 0
        # for all state
        for s in range(state_len):
            # we will get new state value
            new_s = 0
            # for all actions
            for a in range(action_len):
                # get the current transitions list (U,D,L,R)
                transitions_list = env.P[s][a]
                # for all transitions from current state
                for i in transitions_list:
                    transition_prob, next_state, reward, done = i
                    new_s += policy[s, a] * transition_prob * (reward + gamma * state_values[next_state])

            delta = max(delta, np.abs(new_s - state_values[s]))
            state_values[s] = new_s
    return state_values

# Create the FrozenLake environment
env = gym.make('FrozenLake-v1')

# Discount factor gamma
gamma = 0.99
# Initial policy: agents can take actions at equal probability
policy = np.ones((env.observation_space.n, env.action_space.n)) / env.action_space.n
# Initial state values
state_values = np.zeros(env.observation_space.n)
theta = 0.0001

print("****** Initial policy ******")
print(policy)
print("****** Gamma (discount factor) ******")
print(gamma)
print("****** Theta ******")
print(theta)
state_values = policy_evaluation(env, policy, gamma, theta, state_values)
print("****** Best state values ******")
print(np.round(state_values.reshape(4, 4), 3))
print("NOTICE: state values are higher as you get closer to the goal.")


****** Initial policy ******
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
****** Gamma (discount factor) ******
0.99
****** Theta ******
0.0001
****** Best state values ******
[[0.012 0.01  0.019 0.009]
 [0.015 0.    0.039 0.   ]
 [0.033 0.084 0.138 0.   ]
 [0.    0.17  0.434 0.   ]]
NOTICE: state values are higher as you get closer to the goal.
